# Generated by Django 5.0.1 on 2024-01-11 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomePage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='flights',
            field=models.ManyToManyField(related_name='bookings', to='HomePage.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomePage.location'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(related_name='flights', to='HomePage.passenger'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_tickets', to='HomePage.booking'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.flight'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_tickets', to='HomePage.passenger'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_tickets', to='HomePage.ticket'),
        ),
        migrations.AddField(
            model_name='flight',
            name='tickets',
            field=models.ManyToManyField(related_name='flights', to='HomePage.ticket'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.ManyToManyField(related_name='booking_tickets', to='HomePage.ticket'),
        ),
    ]
